; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\data\AsmBook5\examples\ch12\VisualCPP\FindArray\findArr.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_FindArray
; Function compile flags: /Ogtpy
; File c:\data\asmbook5\examples\ch12\visualcpp\findarray\findarr.cpp
;	COMDAT _FindArray
_TEXT	SEGMENT
_searchVal$ = 8						; size = 4
_array$ = 12						; size = 4
_count$ = 16						; size = 4
_FindArray PROC						; COMDAT

; 10   : 	for(int i = 0; i < count; i++)

	mov	ecx, DWORD PTR _count$[esp-4]
	xor	eax, eax
	test	ecx, ecx
	push	esi
	jle	SHORT $LN2@FindArray
	mov	edx, DWORD PTR _array$[esp]
	mov	esi, DWORD PTR _searchVal$[esp]
$LL4@FindArray:

; 11   : 	{
; 12   : 		if( array[i] == searchVal )

	cmp	DWORD PTR [edx+eax*4], esi
	je	SHORT $LN8@FindArray
	add	eax, 1
	cmp	eax, ecx
	jl	SHORT $LL4@FindArray
$LN2@FindArray:

; 14   : 	}
; 15   : 
; 16   :   return false;

	xor	al, al
	pop	esi

; 17   : }

	ret	0
$LN8@FindArray:

; 13   : 			return true;

	mov	al, 1
	pop	esi

; 17   : }

	ret	0
_FindArray ENDP
_TEXT	ENDS
END
